### ISSUE TITLE
Forest Giant Upside down

### ISSUE THREAD

**Issue by HallowSL** [Yinigma/EnemySkinKit#2]
For whatever reason, no matter what I do it seems skins over the Forest Giant spawn upside down, I've tried various different fbx export settings, exporting different orientations (starting with the sample file), trying different bones as the transform root.  https://mega.nz/folder/RlpzyDIY#PLzIJ8M_hKuPMaD0PbbxCQ

**Comment by Yinigma** [comment]
In Blender my relevant export settings are:

Scale: 1.0
Apply Scalings: FBX units scale
Forward: Y forward
Up: Z up

Though unity corrects for some of this, so it may not be the issue.

In addition to that, you'll want to ensure that the metarig bone is oriented the same way as in the example armature while the rest of the modded armature is facing the same way the example model is. It's a little hard to tell on the giant, but you can determine which side is the front by using the thumb bones on the example armature.
I also noticed on your armature that some of the bones have a different coordinate system. All of the example models use Y as the direction of the bone. If your armature doesn't match this the bones won't rotate in the way you expect.
If it's still not working let me know. Regardless I'll add the export settings to the readme. I keep forgetting to do that.

**Comment by HallowSL** [comment]
Still wasn't working, I ended up figuring out my own fix. (ended up rotating metarig upside down, and rotating model to face the opposite direction it was originally facing, then exporting dae https://mega.nz/file/x14RGKDQ#fJ8pmptI6A1jRIy0px1PFOExh6crqEGx9qHl0Iq0Rb4)
