### ISSUE TITLE
Bugs I've encountered

### ISSUE THREAD

**Issue by HallowSL** [Yinigma/EnemySkinKit#3]
Snareflea skin refused to attach to ceiling, this error was in console.
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AntlerShed.EnemySkinKit.Vanilla.SnareFleaSkinner.OnClingToCeiling (CentipedeAI instance) (at <d79ea16bfff54944a14be0ffe6407117>:0)
AntlerShed.SkinRegistry.EnemyPatch+<>c__DisplayClass5_0.<PrefixSwitchBehavior>b__23 (AntlerShed.SkinRegistry.Events.EnemyEventHandler handler) (at <50d4183192fa41d19c16cf832d441016>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <787acc3c9a4c471ba7d971300105af24>:0)
AntlerShed.SkinRegistry.EnemyPatch.PrefixSwitchBehavior (EnemyAI __instance, System.Int32 stateIndex) (at <50d4183192fa41d19c16cf832d441016>:0)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::SwitchToBehaviourStateOnLocalClient>(EnemyAI,int)
CentipedeAI.RaycastToCeiling () (at <255c0877f9414c3aa6f1fe5079ac13f3>:0)
(wrapper dynamic-method) CentipedeAI.DMD<CentipedeAI::Update>(CentipedeAI)
```

Ghost Girl when spawned with a skin is seen by all players rather than only the one being haunted by her.

Bracken and Ghost girl skins sometimes bug out and just afk in one spot. https://youtu.be/CCJNz1ZPQcc?t=13

**Comment by Yinigma** [comment]
First I wanna say thanks for reporting all this stuff. Not everyone would take the time to and it really saves me time finding issues with stuff that isn't easily testable.

Second I may take me a while to get to this. I botched a recovery drive when cleaning my personal machine and I'm gonna be out of commission for a bit.

On the bright side, I reckon I know what's going on with the snare flea and ghost girl, so those should be quick fixes when I'm back in operation. As far as the enemies locking up I'm not sure what could even be doing that unless it's crashing somewhere, but if there were stack traces I imagine you would have posted them. A zip file of the offending Bracken and Ghost Girl skins would be helpful in reproducing the bug if you have the time.

**Comment by HallowSL** [comment]
Happy to help, I love this type of modding. 

I'll have to remember to enable the console next time I play with my friends to see if the bracken and ghost girl spit out any errors.

https://thunderstore.io/c/lethal-company/p/HallowsMods/HallowsEnemySkins/
I'll keep you updated on any other bugs I find.

**Comment by Yinigma** [comment]
I've fixed the issue with the ghost girl being visible to non-haunted players and the snare flea crashing when clinging to the ceiling in the common case where its sound effects weren't replaced.

I'm still not sure what could be going on with the bracken and ghost girl becoming inactive but I'll look into it soon.

**Comment by Yinigma** [comment]
Are you still experiencing this issue at all? I was never able to replicate it.
I figure the ghost girl randomly stopping was probably from her being visible from when she wasn't supposed to be. And the bracken is just weird because it's Lethal Company.
