### ISSUE TITLE
Investigating an issue with Spiders

### ISSUE THREAD

**Issue by NeatWolf** [Yinigma/EnemySkinKit#4]
Hi!

I need to apologize as I know how bug reports are supposed to be made, but the level of intricacy here is a bit out of scale.

I'm encountering probably some incompatibility issues with spiders only.

- @[Arachnophilia ](https://thunderstore.io/c/lethal-company/p/SillySquad/Arachnophilia/)on and EnemySkinKit on (plus, @[ColorfulEnemyVarietyWIP v0.5.2 by DistinctBlaze](https://thunderstore.io/c/lethal-company/p/DistinctBlaze/ColorfulEnemyVarietyWIP/)  : The spider throws continuous errors when trying to create a web cocoon from a corpse in the initialization phase.

- Mod @[Aracnophilia ](https://thunderstore.io/c/lethal-company/p/SillySquad/Arachnophilia/) OFF and EnemySkinKit on: the spiders drag their bodies on the floor instead of walking correctly.

I've encountered those while playing with friends so I was unable to pinpoint the error messages in time (I deactivated all the 3 mods, this included, to restore the spiders to their normal behaviour), but I'm anticipating you the issue.
Maybe you have some intuition in the meantime.

Meanwhile, I'm going to investigate and try to provide you more context. Feels weird the spiders are the only ones affected.
The only one thing I can share right now is my profile code: 018f814b-9b3d-2bb1-d3b0-8c2cbc0bb353

I know it's not ideal but I'll get back to you as soon as I can pinpoint the errors in the console.
Is there any other useful info that could help you debug this? Please let me know.

**Comment by Yinigma** [comment]
Gotcha. I reckon it's either something wrong with the events, the animation copying, or both. I'll look into it this weekend.
