### ISSUE TITLE
issues when importing models

### ISSUE THREAD

**Issue by Messier1071** [Yinigma/EnemySkinKit#7]
this might be something dumb on my part but whenever i try to import a model to replace the buttler it
Tposes:
![image](https://github.com/user-attachments/assets/50097859-c358-4983-9835-31435af90718)
becomes a stick figure:
![image](https://github.com/user-attachments/assets/45690702-85cc-4422-93ae-5790fee6bd9a)
or... whatever this is:
![image](https://github.com/user-attachments/assets/282668cc-b183-463b-bba9-2cb0e35eed31)

the box model from the mod works perfectly when imported

if any of the files is needed for testing, i can supply them

thanks in advance

**Comment by Yinigma** [comment]
Are you using the example armature?

**Comment by Messier1071** [comment]
if you mean the armature that comes in the BoxButler.fbx file, Yes
otherwise, no

**Comment by Messier1071** [comment]
> if you mean the armature that comes in the BoxButler.fbx file, Yes otherwise, no

this ended with the stick figure model

**Comment by Yinigma** [comment]
M'kay. Are you using the export settings in the readme? That might be causing the issue in the last image. It looks like it's following the skeleton, but its scale is wrong.
You can also try fixing it by un-ticking the "convert units" in unity. This setting is in the inspector panel for your fbx under the model tab.

**Comment by Messier1071** [comment]
will do

**Comment by Messier1071** [comment]
👍 
problem solved, thank you
